"""
Stage 2: Backfill annotations for the 49 missing UIAutomation activities.

Reads the merged profile references/version-profiles/UiPath.UIAutomation.Activities/25.10.json,
parses each activity's xaml_template, and emits annotation entries for every activity NOT already
in references/annotations/ui_automation.json.

Wizard-only activities (xaml_template: null) get a stub with _unsupported_reason.
Entries generated by this script carry _review_needed: true.

Usage:
    python uipath-core/scripts/backfill_annotations.py
"""

import json
import re
import sys
from pathlib import Path

try:
    from defusedxml.ElementTree import fromstring as _safe_fromstring
    import defusedxml.ElementTree as _safe_ET
except ImportError:
    import xml.etree.ElementTree as _safe_ET
    _safe_fromstring = _safe_ET.fromstring

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
REPO_ROOT = Path(__file__).resolve().parent.parent
PROFILE_PATH = REPO_ROOT / "references" / "version-profiles" / "UiPath.UIAutomation.Activities" / "25.10.json"
ANNOTATIONS_PATH = REPO_ROOT / "references" / "annotations" / "ui_automation.json"

# ---------------------------------------------------------------------------
# Wizard-only activities (xaml_template: null, no stable default shape)
# ---------------------------------------------------------------------------
WIZARD_ONLY = {
    "ApplicationEventTrigger",
    "ExtractUIData",
    "GetAttribute",
    "NAccessibilityCheck",
    "NExtractDataGeneric",
    "NExtractFormDataGeneric",
    "NSetValue",
}

# ---------------------------------------------------------------------------
# Heuristic: attributes whose value looks parameterizable
# Value is parameterizable when:
#   - it is "{x:Null}"  -> output variable / optional arg
#   - its attr name is in KNOWN_PARAM_ATTRS
# ---------------------------------------------------------------------------
KNOWN_PARAM_ATTRS = {
    # output variables
    "Result", "TextString", "Text", "CurrentUrl", "Children",
    "SessionData", "SavedTo", "OutFile", "OutImage",
    # input arguments
    "Transaction", "Prefix", "Item", "Url", "ScriptCode",
    "InputParameter", "ScriptOutput", "FilterTarget", "Mode",
    "SessionData",
    # SAP outputs
    "MessageData", "MessageId", "MessageNumber", "MessageText", "MessageType",
    # display name is always param
    "DisplayName",
}

# Attributes that are always fixed (never parameterised by user)
ALWAYS_FIXED_ATTRS = {
    "HealingAgentBehavior", "InteractionMode", "Version", "ActivateBefore",
    "ClickBeforeMode", "ClipboardMode", "ClickType", "MouseButton",
    "KeyModifiers", "Action", "Direction", "MovementUnits",
    "Color", "FileNameMode", "LimitExtractionTo",
    "Enabled", "SchedulingMode",
    "ScopeGuid", "TriggerId",
}

# Known enum values per attribute
KNOWN_ENUMS: dict[str, list[str]] = {
    "HealingAgentBehavior": ["SameAsCard", "Disabled", "Job"],
    "InteractionMode": ["HardwareEvents", "SimulateClick", "ChromiumApi", "SameAsCard"],
    "ClickType": ["Single", "Double"],
    "MouseButton": ["Left", "Right", "Middle"],
    "Direction": ["Down", "Up", "Left", "Right"],
    "Action": ["Check", "Uncheck", "Toggle"],
    "FileNameMode": ["None", "FullPath", "FileName"],
    "LimitExtractionTo": ["Rows", "Pages"],
    "SchedulingMode": ["Sequential", "Parallel"],
    "ClickBeforeMode": ["None", "Single"],
    "Option": ["Single", "All"],
    "ClipboardMode": ["Never", "Always", "WhenNeeded"],
    "EmptyFieldMode": ["SingleLine", "MultiLine", "None"],
}


def _is_null_value(val: str) -> bool:
    return val == "{x:Null}"


def _is_fixed(attr: str, val: str) -> bool:
    """Return True if this attribute should go in fixed_attrs."""
    if attr in ALWAYS_FIXED_ATTRS:
        return True
    if _is_null_value(val):
        return False
    if attr in KNOWN_PARAM_ATTRS:
        return False
    # If value looks like a GUID, treat as fixed
    if re.match(r'^[0-9a-f\-]{36}$', val, re.IGNORECASE):
        return True
    return True  # default: treat as fixed unless we know better


def _snake(name: str) -> str:
    """Convert CamelCase to snake_case."""
    s1 = re.sub(r'(.)([A-Z][a-z]+)', r'\1_\2', name)
    return re.sub(r'([a-z0-9])([A-Z])', r'\1_\2', s1).lower()


def _build_param_entry(attr: str) -> dict:
    """Build a params entry for a parameterizable attribute."""
    return {
        "attr": attr,
        "required": False,
        "default": None,
        "enum": KNOWN_ENUMS.get(attr),
        "escape": "xml" if attr == "DisplayName" else None,
        "bracket_wrap": False,
        "type": "string",
    }


def _build_standard_params(activity_name: str) -> dict:
    """Build the standard params block that nearly every activity needs."""
    return {
        "display_name": {
            "attr": "DisplayName",
            "required": True,
            "default": None,
            "enum": None,
            "escape": "xml",
            "bracket_wrap": False,
            "type": "string",
        },
        "id_ref": {
            "attr": "sap2010:WorkflowViewState.IdRef",
            "required": True,
            "default": None,
            "enum": None,
            "escape": None,
            "bracket_wrap": False,
            "type": "id_ref",
        },
        "scope_id": {
            "attr": "ScopeIdentifier",
            "required": True,
            "default": None,
            "enum": None,
            "escape": None,
            "bracket_wrap": False,
            "type": "scope_id",
        },
    }


def _has_selector_target(properties: list[str]) -> bool:
    return "Target" in properties


def _build_annotation(name: str, profile_entry: dict) -> dict:
    """Build an annotation entry from a profile entry."""
    template = profile_entry.get("xaml_template")
    namespace_prefix = profile_entry.get("namespace_prefix", "uix")
    properties = profile_entry.get("properties", [])

    gen_name = "gen_" + _snake(name)
    tag = f"{namespace_prefix}:{name}" if namespace_prefix else name

    params = _build_standard_params(name)
    fixed_attrs: dict[str, str] = {}
    child_elements: dict = {}

    if template:
        # Strip surrounding whitespace/newlines for single-line parsing
        # Only parse the root element attributes (not full tree for complex templates)
        # Extract root element only to avoid namespace issues
        root_match = re.match(r'^<([^\s/>]+)\s*((?:[^>](?!/>))*[^>]?)?\s*/?>', template.strip(), re.DOTALL)
        if root_match:
            attrs_str = root_match.group(2) or ""
            # Parse attributes out of the opening tag
            for m in re.finditer(r'(\w[\w.:]*)\s*=\s*"([^"]*)"', attrs_str):
                attr, val = m.group(1), m.group(2)
                if _is_null_value(val) or attr in KNOWN_PARAM_ATTRS:
                    # parameterizable
                    key = _snake(attr)
                    params[key] = _build_param_entry(attr)
                elif _is_fixed(attr, val):
                    fixed_attrs[attr] = val

    # Add selector param if activity has Target property
    if _has_selector_target(properties):
        params["selector"] = {
            "attr": None,
            "required": True,
            "default": None,
            "enum": None,
            "escape": None,
            "bracket_wrap": False,
            "type": "selector_param",
        }
        child_elements[f"{name}.Target"] = {
            "type": "selector",
            "content": None,
        }

    # Add obj_repo param (standard)
    params["obj_repo"] = {
        "attr": None,
        "required": False,
        "default": None,
        "enum": None,
        "escape": None,
        "bracket_wrap": False,
        "type": "obj_repo_param",
    }

    # Detect scope activities (have Body child element in template)
    if template and ".Body>" in template:
        child_elements[f"{name}.Body"] = {
            "type": "activity_action",
            "content": "ActivityAction x:TypeArguments='x:Object' with DelegateInArgument WSSessionData and Sequence Do body",
        }
        # Remove obj_repo for scope activities — they take a body not a target interaction
        params.pop("obj_repo", None)
        params.pop("selector", None)
        child_elements.pop(f"{name}.Target", None)

    entry: dict = {
        "gen_function": gen_name,
        "element_tag": tag,
        "params": params,
        "fixed_attrs": fixed_attrs,
        "child_elements": child_elements,
        "conditional_attrs": {},
        "_review_needed": True,
    }

    # SAP session note
    if name.startswith("NSAP") and name not in ("NSAPLogon",):
        entry["_sap_note"] = "Must be used inside an NSAPLogon scope. Generator emits a warning if no SAP session context is present."

    return entry


def main() -> None:
    # Load profile
    with open(PROFILE_PATH, encoding="utf-8") as f:
        profile = json.load(f)

    # Load existing annotations
    with open(ANNOTATIONS_PATH, encoding="utf-8") as f:
        annotations = json.load(f)

    existing = set(annotations["activities"].keys())
    activities = profile["activities"]

    added_count = 0
    wizard_count = 0
    skipped_count = 0

    # Category counters
    sap_count = 0
    scope_count = 0
    browser_count = 0
    ocr_count = 0
    trigger_count = 0
    other_count = 0

    for name, entry in activities.items():
        if name in existing:
            skipped_count += 1
            continue

        if name in WIZARD_ONLY or entry.get("xaml_template") is None:
            annotations["activities"][name] = {
                "_unsupported_reason": "wizard-only",
                "_review_needed": False,
            }
            wizard_count += 1
            continue

        annotation = _build_annotation(name, entry)
        annotations["activities"][name] = annotation
        added_count += 1

        # Category tally
        if name.startswith("NSAP"):
            sap_count += 1
        elif "Scope" in name or "Card" in name or "Logon" in name:
            scope_count += 1
        elif "Browser" in name or "Url" in name or "Navigate" in name:
            browser_count += 1
        elif "OCR" in name:
            ocr_count += 1
        elif "Trigger" in name:
            trigger_count += 1
        else:
            other_count += 1

    # Write back
    with open(ANNOTATIONS_PATH, "w", encoding="utf-8") as f:
        json.dump(annotations, f, indent=2, ensure_ascii=False)
        f.write("\n")

    print(f"Backfill complete:")
    print(f"  Skipped (already existed): {skipped_count}")
    print(f"  Added (with _review_needed): {added_count}")
    print(f"    SAP activities:     {sap_count}")
    print(f"    Scope/Card:         {scope_count}")
    print(f"    Browser/URL:        {browser_count}")
    print(f"    OCR engines:        {ocr_count}")
    print(f"    Event triggers:     {trigger_count}")
    print(f"    Other modern UI:    {other_count}")
    print(f"  Wizard-only stubs:    {wizard_count}")
    total_after = len(annotations["activities"])
    print(f"  Total entries now:    {total_after}")

    # Heuristic hit-rate: entries with at least one param beyond display_name/id_ref/scope_id
    enriched = sum(
        1 for k, v in annotations["activities"].items()
        if isinstance(v, dict)
        and "_unsupported_reason" not in v
        and len(v.get("params", {})) > 3  # more than just display_name+id_ref+scope_id
    )
    total_real = sum(
        1 for v in annotations["activities"].values()
        if isinstance(v, dict) and "_unsupported_reason" not in v
    )
    hit_rate = enriched / total_real * 100 if total_real else 0
    print(f"\nHeuristic hit rate (entries with >3 params): {enriched}/{total_real} = {hit_rate:.0f}%")


if __name__ == "__main__":
    main()
