"""
Backfill annotations for activities present in a version profile but
absent from the annotations corpus. Originally scoped to UIAutomation
25.10; the --profile / --annotations flags generalize it to any
package.

Reads a version-profile JSON, parses each activity's xaml_template,
and emits annotation entries for every activity NOT already in the
target annotations file. Wizard-only activities (xaml_template: null)
get a stub with _unsupported_reason. Entries generated by this script
carry _review_needed: true so the data-driven dispatcher gates them
behind UIPATH_ALLOW_REVIEW_NEEDED until human-validated.

Usage:
    # Default: UIAutomation 25.10 -> ui_automation.json (legacy)
    python uipath-core/scripts/backfill_annotations.py

    # Backfill any package
    python uipath-core/scripts/backfill_annotations.py \\
        --profile uipath-core/references/version-profiles/UiPath.Excel.Activities/3.4.json \\
        --annotations uipath-core/references/annotations/excel_extended.json

    # --all: walk every (package, version) pair under version-profiles/
    # and append into per-package extended annotation files.
    python uipath-core/scripts/backfill_annotations.py --all
"""

import argparse
import json
import re
import sys
from pathlib import Path

try:
    from defusedxml.ElementTree import fromstring as _safe_fromstring
    import defusedxml.ElementTree as _safe_ET
except ImportError:
    import xml.etree.ElementTree as _safe_ET
    _safe_fromstring = _safe_ET.fromstring

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
REPO_ROOT = Path(__file__).resolve().parent.parent
PROFILE_PATH = REPO_ROOT / "references" / "version-profiles" / "UiPath.UIAutomation.Activities" / "25.10.json"
ANNOTATIONS_PATH = REPO_ROOT / "references" / "annotations" / "ui_automation.json"

# ---------------------------------------------------------------------------
# Wizard-only activities (xaml_template: null, no stable default shape)
# ---------------------------------------------------------------------------
WIZARD_ONLY = {
    "ApplicationEventTrigger",
    "ExtractUIData",
    "GetAttribute",
    "NAccessibilityCheck",
    "NExtractDataGeneric",
    "NExtractFormDataGeneric",
    "NSetValue",
}

# ---------------------------------------------------------------------------
# Heuristic: attributes whose value looks parameterizable
# Value is parameterizable when:
#   - it is "{x:Null}"  -> output variable / optional arg
#   - its attr name is in KNOWN_PARAM_ATTRS
# ---------------------------------------------------------------------------
KNOWN_PARAM_ATTRS = {
    # output variables
    "Result", "TextString", "Text", "CurrentUrl", "Children",
    "SessionData", "SavedTo", "OutFile", "OutImage",
    # input arguments
    "Transaction", "Prefix", "Item", "Url", "ScriptCode",
    "InputParameter", "ScriptOutput", "FilterTarget", "Mode",
    "SessionData",
    # SAP outputs
    "MessageData", "MessageId", "MessageNumber", "MessageText", "MessageType",
    # display name is always param
    "DisplayName",
}

# Attributes that are always fixed (never parameterised by user)
ALWAYS_FIXED_ATTRS = {
    "HealingAgentBehavior", "InteractionMode", "Version", "ActivateBefore",
    "ClickBeforeMode", "ClipboardMode", "ClickType", "MouseButton",
    "KeyModifiers", "Action", "Direction", "MovementUnits",
    "Color", "FileNameMode", "LimitExtractionTo",
    "Enabled", "SchedulingMode",
    "ScopeGuid", "TriggerId",
}

# Known enum values per attribute
KNOWN_ENUMS: dict[str, list[str]] = {
    "HealingAgentBehavior": ["SameAsCard", "Disabled", "Job"],
    "InteractionMode": ["HardwareEvents", "SimulateClick", "ChromiumApi", "SameAsCard"],
    "ClickType": ["Single", "Double"],
    "MouseButton": ["Left", "Right", "Middle"],
    "Direction": ["Down", "Up", "Left", "Right"],
    "Action": ["Check", "Uncheck", "Toggle"],
    "FileNameMode": ["None", "FullPath", "FileName"],
    "LimitExtractionTo": ["Rows", "Pages"],
    "SchedulingMode": ["Sequential", "Parallel"],
    "ClickBeforeMode": ["None", "Single"],
    "Option": ["Single", "All"],
    "ClipboardMode": ["Never", "Always", "WhenNeeded"],
    "EmptyFieldMode": ["SingleLine", "MultiLine", "None"],
}


def _is_null_value(val: str) -> bool:
    return val == "{x:Null}"


def _is_fixed(attr: str, val: str) -> bool:
    """Return True if this attribute should go in fixed_attrs."""
    if attr in ALWAYS_FIXED_ATTRS:
        return True
    if _is_null_value(val):
        return False
    if attr in KNOWN_PARAM_ATTRS:
        return False
    # If value looks like a GUID, treat as fixed
    if re.match(r'^[0-9a-f\-]{36}$', val, re.IGNORECASE):
        return True
    return True  # default: treat as fixed unless we know better


def _snake(name: str) -> str:
    """Convert CamelCase to snake_case."""
    s1 = re.sub(r'(.)([A-Z][a-z]+)', r'\1_\2', name)
    return re.sub(r'([a-z0-9])([A-Z])', r'\1_\2', s1).lower()


def _build_param_entry(attr: str) -> dict:
    """Build a params entry for a parameterizable attribute."""
    return {
        "attr": attr,
        "required": False,
        "default": None,
        "enum": KNOWN_ENUMS.get(attr),
        "escape": "xml" if attr == "DisplayName" else None,
        "bracket_wrap": False,
        "type": "string",
    }


def _build_standard_params(activity_name: str) -> dict:
    """Build the standard params block that nearly every activity needs."""
    return {
        "display_name": {
            "attr": "DisplayName",
            "required": True,
            "default": None,
            "enum": None,
            "escape": "xml",
            "bracket_wrap": False,
            "type": "string",
        },
        "id_ref": {
            "attr": "sap2010:WorkflowViewState.IdRef",
            "required": True,
            "default": None,
            "enum": None,
            "escape": None,
            "bracket_wrap": False,
            "type": "id_ref",
        },
        "scope_id": {
            "attr": "ScopeIdentifier",
            "required": True,
            "default": None,
            "enum": None,
            "escape": None,
            "bracket_wrap": False,
            "type": "scope_id",
        },
    }


def _has_selector_target(properties: list[str]) -> bool:
    return "Target" in properties


def _build_annotation(name: str, profile_entry: dict) -> dict:
    """Build an annotation entry from a profile entry."""
    template = profile_entry.get("xaml_template")
    namespace_prefix = profile_entry.get("namespace_prefix", "uix")
    properties = profile_entry.get("properties", [])

    gen_name = "gen_" + _snake(name)
    tag = f"{namespace_prefix}:{name}" if namespace_prefix else name

    params = _build_standard_params(name)
    fixed_attrs: dict[str, str] = {}
    child_elements: dict = {}

    if template:
        # Strip surrounding whitespace/newlines for single-line parsing
        # Only parse the root element attributes (not full tree for complex templates)
        # Extract root element only to avoid namespace issues
        root_match = re.match(r'^<([^\s/>]+)\s*((?:[^>](?!/>))*[^>]?)?\s*/?>', template.strip(), re.DOTALL)
        if root_match:
            attrs_str = root_match.group(2) or ""
            # Parse attributes out of the opening tag
            for m in re.finditer(r'(\w[\w.:]*)\s*=\s*"([^"]*)"', attrs_str):
                attr, val = m.group(1), m.group(2)
                if _is_null_value(val) or attr in KNOWN_PARAM_ATTRS:
                    # parameterizable
                    key = _snake(attr)
                    params[key] = _build_param_entry(attr)
                elif _is_fixed(attr, val):
                    fixed_attrs[attr] = val

    # Add selector param if activity has Target property
    if _has_selector_target(properties):
        params["selector"] = {
            "attr": None,
            "required": True,
            "default": None,
            "enum": None,
            "escape": None,
            "bracket_wrap": False,
            "type": "selector_param",
        }
        child_elements[f"{name}.Target"] = {
            "type": "selector",
            "content": None,
        }

    # Add obj_repo param (standard)
    params["obj_repo"] = {
        "attr": None,
        "required": False,
        "default": None,
        "enum": None,
        "escape": None,
        "bracket_wrap": False,
        "type": "obj_repo_param",
    }

    # Detect scope activities (have Body child element in template)
    if template and ".Body>" in template:
        child_elements[f"{name}.Body"] = {
            "type": "activity_action",
            "content": "ActivityAction x:TypeArguments='x:Object' with DelegateInArgument WSSessionData and Sequence Do body",
        }
        # Remove obj_repo for scope activities — they take a body not a target interaction
        params.pop("obj_repo", None)
        params.pop("selector", None)
        child_elements.pop(f"{name}.Target", None)

    entry: dict = {
        "gen_function": gen_name,
        "element_tag": tag,
        "params": params,
        "fixed_attrs": fixed_attrs,
        "child_elements": child_elements,
        "conditional_attrs": {},
        "_review_needed": True,
    }

    # SAP session note
    if name.startswith("NSAP") and name not in ("NSAPLogon",):
        entry["_sap_note"] = "Must be used inside an NSAPLogon scope. Generator emits a warning if no SAP session context is present."

    return entry


PACKAGE_TO_ANNOTATIONS_FILE = {
    "UiPath.UIAutomation.Activities": "ui_automation.json",
    "UiPath.Excel.Activities": "excel_extended.json",
    "UiPath.Mail.Activities": "mail_extended.json",
    "UiPath.System.Activities": "system_extended.json",
    "UiPath.Testing.Activities": "testing.json",
    "UiPath.Persistence.Activities": "persistence_extended.json",
}


def _collect_all_known_activity_names(annot_root: Path) -> set[str]:
    """Build the lower-cased set of activity names across every annotations/*.json.

    The dispatcher merges all files into a single lower-cased cache, so an
    activity present in any one file is "already known" and must not be
    re-added to a different file.
    """
    known: set[str] = set()
    if not annot_root.exists():
        return known
    for jf in annot_root.glob("*.json"):
        try:
            d = json.loads(jf.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            continue
        for name in (d.get("activities") or {}).keys():
            known.add(name.lower())
    return known


def _backfill_one(profile_path: Path, annotations_path: Path) -> dict:
    """Backfill a single (profile, annotations) pair. Returns counters dict."""
    with open(profile_path, encoding="utf-8") as f:
        profile = json.load(f)

    if annotations_path.exists():
        with open(annotations_path, encoding="utf-8") as f:
            annotations = json.load(f)
    else:
        annotations = {"activities": {}}

    # Skip anything already known across ALL annotation files (the dispatcher
    # merges them lower-cased, so a duplicate in a different file would
    # silently override the canonical entry).
    annot_root = annotations_path.parent
    all_known_lc = _collect_all_known_activity_names(annot_root)
    activities = profile.get("activities", {})

    added = 0
    wizard = 0
    skipped = 0

    for name, entry in activities.items():
        if name.lower() in all_known_lc:
            skipped += 1
            continue

        # Wizard-only detection: only when the profile has no xaml_template
        # at all, OR the activity name is in the curated WIZARD_ONLY set.
        # Note: harvestable=False does NOT imply wizard-only — many WF4
        # built-ins (Delay, Assign, If, ...) are non-harvestable but have
        # hand-authored templates that drive correct generation.
        is_wizard = (
            name in WIZARD_ONLY
            or entry.get("xaml_template") is None
        )
        if is_wizard:
            annotations.setdefault("activities", {})[name] = {
                "_unsupported_reason": "wizard-only",
                "_review_needed": False,
            }
            wizard += 1
            all_known_lc.add(name.lower())
            continue

        annotations.setdefault("activities", {})[name] = _build_annotation(name, entry)
        added += 1
        all_known_lc.add(name.lower())

    annotations_path.parent.mkdir(parents=True, exist_ok=True)
    with open(annotations_path, "w", encoding="utf-8") as f:
        json.dump(annotations, f, indent=2, ensure_ascii=False)
        f.write("\n")

    return {
        "profile": str(profile_path),
        "annotations": str(annotations_path),
        "skipped": skipped,
        "added": added,
        "wizard": wizard,
        "total_after": len(annotations.get("activities", {})),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--profile", type=Path, help="path to a version-profile JSON file")
    parser.add_argument("--annotations", type=Path, help="path to the target annotations JSON")
    parser.add_argument("--all", action="store_true", help="walk every profile under references/version-profiles/")
    args = parser.parse_args()

    if args.all:
        profiles_root = REPO_ROOT / "references" / "version-profiles"
        annot_root = REPO_ROOT / "references" / "annotations"
        results = []
        for pkg_dir in sorted(profiles_root.iterdir()):
            if not pkg_dir.is_dir():
                continue
            target_file = PACKAGE_TO_ANNOTATIONS_FILE.get(pkg_dir.name)
            if not target_file:
                print(f"  [SKIP] no annotation mapping for package {pkg_dir.name}", file=sys.stderr)
                continue
            for prof in sorted(pkg_dir.glob("*.json")):
                ann = annot_root / target_file
                results.append(_backfill_one(prof, ann))
        # Aggregate report
        total_added = sum(r["added"] for r in results)
        total_skipped = sum(r["skipped"] for r in results)
        total_wizard = sum(r["wizard"] for r in results)
        print("Backfill --all summary:")
        for r in results:
            prof_rel = Path(r["profile"]).relative_to(REPO_ROOT.parent)
            ann_rel = Path(r["annotations"]).relative_to(REPO_ROOT.parent)
            print(f"  {prof_rel} -> {ann_rel}: +{r['added']}  ={r['skipped']}  wiz={r['wizard']}  total={r['total_after']}")
        print(f"Totals: added={total_added}  skipped={total_skipped}  wizard={total_wizard}")
        return

    profile_path = args.profile or PROFILE_PATH
    annotations_path = args.annotations or ANNOTATIONS_PATH
    r = _backfill_one(profile_path, annotations_path)
    print(f"Backfill complete:")
    print(f"  Profile:                      {r['profile']}")
    print(f"  Annotations target:           {r['annotations']}")
    print(f"  Skipped (already existed):    {r['skipped']}")
    print(f"  Added (with _review_needed):  {r['added']}")
    print(f"  Wizard-only stubs:            {r['wizard']}")
    print(f"  Total entries now:            {r['total_after']}")


if __name__ == "__main__":
    main()
